//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public int photographer_id { get; set; }
        public int client_id { get; set; }
        public string comment1 { get; set; }
        public bool is_approved { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual client client { get; set; }
        public virtual photographer photographer { get; set; }
    }
}
