//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sightEntities : DbContext
    {
        public sightEntities()
            : base("name=sightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<commentsHome> commentsHomes { get; set; }
        public virtual DbSet<photo_sessions> photo_sessions { get; set; }
        public virtual DbSet<photographer_cities> photographer_cities { get; set; }
        public virtual DbSet<photographer> photographers { get; set; }
        public virtual DbSet<PhotographerType> PhotographerTypes { get; set; }
        public virtual DbSet<PhotographyType> PhotographyTypes { get; set; }
        public virtual DbSet<photosAdmin> photosAdmins { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<PhotographerPricing> PhotographerPricings { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
    }
}
