//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photographer_cities
    {
        public int photographer_id { get; set; }
        public int city_id { get; set; }
        public string note { get; set; }
    
        public virtual city city { get; set; }
        public virtual photographer photographer { get; set; }
    }
}
