//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotographerType
    {
        public int PhotographerID { get; set; }
        public int TypeID { get; set; }
        public string note { get; set; }
    
        public virtual photographer photographer { get; set; }
        public virtual PhotographyType PhotographyType { get; set; }
    }
}
