//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo_sessions
    {
        public int id { get; set; }
        public int photographer_id { get; set; }
        public int client_id { get; set; }
        public int city_id { get; set; }
        public int TypeID { get; set; }
        public System.DateTime session_date { get; set; }
        public System.TimeSpan session_time { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public int howMany { get; set; }
        public Nullable<int> pricing_id { get; set; }
        public string theDescription { get; set; }
        public string session_minutes { get; set; }
        public string phone { get; set; }
    
        public virtual city city { get; set; }
        public virtual client client { get; set; }
        public virtual photographer photographer { get; set; }
        public virtual PhotographyType PhotographyType { get; set; }
        public virtual PhotographerPricing PhotographerPricing { get; set; }
    }
}
