//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotographerPricing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotographerPricing()
        {
            this.photo_sessions = new HashSet<photo_sessions>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PhotographerID { get; set; }
        public int PhotographyTypeID { get; set; }
        public decimal PriceOneHour { get; set; }
        public decimal PriceOneAndHalfHour { get; set; }
        public decimal PriceTwoHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<photo_sessions> photo_sessions { get; set; }
        public virtual photographer photographer { get; set; }
        public virtual PhotographyType PhotographyType { get; set; }
    }
}
