//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotographerPricing
    {
        public int ID { get; set; }
        public Nullable<int> PhotographerID { get; set; }
        public string PhotographyType { get; set; }
        public decimal PriceOneHour { get; set; }
        public decimal PriceOneAndHalfHour { get; set; }
        public decimal PriceTwoHours { get; set; }
    
        public virtual photographer photographer { get; set; }
    }
}
