//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int ID { get; set; }
        public Nullable<int> PhotographerId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> theCounter { get; set; }
        public bool status { get; set; }
    
        public virtual photographer photographer { get; set; }
    }
}
